name: myapp
services:
  backend1:
    image: apptest1
    user: appuser
    container_name: apptestcon1
    cpus: "0.5"
    mem_limit: 400m
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - app_data1:/data
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: ["/start.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 2

  backend2:
    image: apptest1
    user: appuser
    container_name: apptestcon2
    cpus: "0.5"
    mem_limit: 400m
    ports:
      - "8081:80"
    env_file:
      - .env
    volumes:
      - app_data2:/data
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: ["/start.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 2

  backend3:
    image: apptest1
    user: appuser
    container_name: apptestcon3
    cpus: "0.5"
    mem_limit: 400m
    ports:
      - "8082:80"
    env_file:
      - .env
    volumes:
      - app_data3:/data
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: ["/start.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 2

  db:
    image: docker.io/library/postgres:16
    container_name: postgres_db
    cpus: "0.5"
    mem_limit: 1g
    environment:
      POSTGRES_USER: leojr
      POSTGRES_PASSWORD: "urmotherisbitchlikeurfatherex"
      POSTGRES_DB: userdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leojr -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  app_data1:
  app_data2:
  app_data3:
  db_data: