

CREATE TABLE IF NOT EXISTS drive (
    email TEXT PRIMARY KEY,
    id UUID,
    access_token TEXT,
    refresh_token TEXT,
    scopes JSONB DEFAULT '{}'::jsonb,
    token_expire TIMESTAMP,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    connected SMALLINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS gmail (
    email TEXT PRIMARY KEY,
    id UUID,
    token_expire TIMESTAMP,
    access_token TEXT,
    refresh_token TEXT,
    timestamp TIMESTAMPTZ,
    file BIGINT,
    hash_file TEXT,
    last_history_id TEXT
);

CREATE TABLE IF NOT EXISTS instagram (
    account_id BIGINT PRIMARY KEY,
    id UUID,
    access_token TEXT,
    timestamp TIMESTAMPTZ,
    token_expire TIMESTAMPTZ,
    scopes JSONB DEFAULT '{}'::jsonb,
    username TEXT,
    file BIGINT,
    hash_file TEXT
);

CREATE TABLE IF NOT EXISTS paypal (
    paypal_order_id TEXT PRIMARY KEY,
    id UUID,
    cart_id TEXT,
    status TEXT,
    paid INT2,
    updated_at TIMESTAMPTZ,
    plan TEXT
);

CREATE TABLE IF NOT EXISTS paypal_verify (
    id UUID PRIMARY KEY,
    idempotency_key TEXT,
    request_hash TEXT,
    response JSON DEFAULT '{}'::json,
    event_id TEXT,
    created_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS pinterst (
    account_id TEXT PRIMARY KEY,
    id UUID,
    timestamp TIMESTAMPTZ DEFAULT now(),
    username TEXT,
    access_token TEXT,
    token_expire TIMESTAMPTZ,
    file BIGINT,
    hash_file TEXT,
    refresh_token TEXT
);

CREATE TABLE IF NOT EXISTS razorpay (
    order_id TEXT PRIMARY KEY,
    id UUID,
    plan_id TEXT,
    status TEXT,
    updates_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS razorpay_verify (
    key TEXT PRIMARY KEY,
    id UUID,
    status TEXT,
    response_json TEXT,
    created_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS threads (
    account_id TEXT PRIMARY KEY,
    id UUID,
    access_token TEXT,
    token_expire TIMESTAMPTZ,
    username TEXT,
    file BIGINT,
    hash_file TEXT,
    refresh_token TEXT,
    timestamp TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS whatsapp (
    account_id BIGINT PRIMARY KEY,
    id UUID,
    access_token TEXT,
    token_expire TIMESTAMP,
    scopes JSONB DEFAULT '{}'::jsonb,
    timestamp TIMESTAMPTZ,
    phone_no BIGINT,
    file BIGINT,
    hash_file TEXT
);

CREATE TABLE IF NOT EXISTS x (
    account_id TEXT PRIMARY KEY,
    id UUID,
    refresh_token TEXT,
    access_token TEXT,
    token_expire TIMESTAMPTZ,
    username TEXT,
    file BIGINT,
    hash_file TEXT,
    timestamp TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS youtube (
    account_id TEXT PRIMARY KEY,
    id UUID,
    channel_title TEXT,
    access_token TEXT,
    refresh_token TEXT,
    file BIGINT,
    hash_file TEXT,
    token_expire TIMESTAMPTZ,
    timestamp TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now(),
    name TEXT DEFAULT '',
    gmail TEXT,
    phone_number BIGINT,
    gdrive BOOLEAN,
    instagram BOOLEAN,
    whatsapp BOOLEAN,
    x BOOLEAN,
    pinterst BOOLEAN,
    threads BOOLEAN,
    youtube BOOLEAN,
    paid TEXT
);

CREATE TABLE IF NOT EXISTS userdetails (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT,
    user_id UUID UNIQUE
);

CREATE TABLE IF NOT EXISTS schedule (
    id BIGINT PRIMARY KEY,
    user_id TEXT,
    time TIMESTAMPTZ,
    type TEXT,
    container_id TEXT,
    access_token TEXT,
    media_id TEXT,
    hour INTEGER,
    text1 TEXT,
    text2 TEXT,
    text3 TEXT,
    taken INTEGER
);

CREATE TABLE IF NOT EXISTS workflow (
    id TEXT PRIMARY KEY,
    time TIMESTAMPTZ,
    message TEXT,
    comment TEXT
);

CREATE TABLE IF NOT EXISTS rate_limit (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    Start_time TIMESTAMPTZ NOT NULL,
    End_time TIMESTAMPTZ NOT NULL,
    request_count INTEGER NOT NULL DEFAULT 0
);


ALTER TABLE drive           ADD CONSTRAINT fk_drive_user           FOREIGN KEY (id) REFERENCES users (user_id) ON DELETE CASCADE;
ALTER TABLE gmail           ADD CONSTRAINT fk_gmail_user           FOREIGN KEY (id) REFERENCES users (user_id) ON DELETE CASCADE;
ALTER TABLE instagram       ADD CONSTRAINT fk_instagram_user       FOREIGN KEY (id) REFERENCES users (user_id) ON DELETE CASCADE;
ALTER TABLE paypal          ADD CONSTRAINT fk_paypal_user          FOREIGN KEY (id) REFERENCES users (user_id) ON DELETE CASCADE;
ALTER TABLE paypal_verify   ADD CONSTRAINT fk_paypal_verify_user   FOREIGN KEY (id) REFERENCES users (user_id) ON DELETE CASCADE;
ALTER TABLE pinterst        ADD CONSTRAINT fk_pinterst_user        FOREIGN KEY (id) REFERENCES users (user_id) ON DELETE CASCADE;
ALTER TABLE razorpay        ADD CONSTRAINT fk_razorpay_user        FOREIGN KEY (id) REFERENCES users (user_id) ON DELETE CASCADE;
ALTER TABLE razorpay_verify ADD CONSTRAINT fk_razorpay_verify_user FOREIGN KEY (id) REFERENCES users (user_id) ON DELETE CASCADE;
ALTER TABLE threads         ADD CONSTRAINT fk_threads_user         FOREIGN KEY (id) REFERENCES users (user_id) ON DELETE CASCADE;
ALTER TABLE whatsapp        ADD CONSTRAINT fk_whatsapp_user        FOREIGN KEY (id) REFERENCES users (user_id) ON DELETE CASCADE;
ALTER TABLE x               ADD CONSTRAINT fk_x_user               FOREIGN KEY (id) REFERENCES users (user_id) ON DELETE CASCADE;
ALTER TABLE youtube         ADD CONSTRAINT fk_youtube_user         FOREIGN KEY (id) REFERENCES users (user_id) ON DELETE CASCADE;
ALTER TABLE userdetails     ADD CONSTRAINT fk_userdetails          FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;
ALTER TABLE rate_limit      ADD CONSTRAINT fk_rate_limit           FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;
 
